CREATE DATABASE streetwisefitness COLLATE utf8_general_ci;

USE streetwisefitness; 

CREATE TABLE usuario (
    COD_USUARIO INT (10) AUTO_INCREMENT PRIMARY KEY,
    NOMBRES VARCHAR(50),
    APELLIDOS VARCHAR(50),
    CORREO VARCHAR(50),
    CELULAR INT(10),
    FECHA_NACIMIENTO DATE,
    CONTRASEÑA LONGTEXT NOT NULL
)

INSERT INTO usuario VALUES
(5, 'Jorel', 'Varrero')
(6, 'Jonatan', 'Barco')