CREATE DATABASE streetwise COLLATE utf8_general_ci;

USE steetwise; 

CREATE TABLE usuario (
    COD_USUARIO INT (12) AUTO_INCREMENT PRIMARY KEY,
    NOMBRES VARCHAR(50),
    APELLIDOS VARCHAR(50),
    CORREO VARCHAR(50),
    CELULAR INT(12),
    FECHA_NACIMIENTO DATE,
    CONTRASEÑA LONGTEXT NOT NULL
)